### ISSUE TITLE
Error while run activator run 

### ISSUE THREAD

**Issue by hendisantika** [pvoznenko/play-slick-angular-test-example#2]
Nice post,

I want to ask.
Error while run activator run 

```
Compilation error
 cannot access controllers.ReverseAssets
In /home/hendisantika/play/play-slick-angular-test-example/conf/routes (line number not found)
```

Thanks

**Comment by pvoznenko** [comment]
Hi @hendisantika , thanks for reporting.

This repo is more than 2 years old, so might be that some thing is not working anymore, especially with new versions of Activator.

Could you please tell me which version of Activator you are using?

Try with SBT instead of Activator:

```
$ sbt run
```

**Comment by hendisantika** [comment]
I am using : 
1. Activator 1.3.12
2. Play Framework 2.5.10
3. Scala Version 2.11.8

**Comment by pvoznenko** [comment]
@hendisantika code mentioned in this repo might not work in play 2.5, since here project with play 2.3. Play team changed a lot in between this versions.

Could be that `controllers.ReverseAssets` changed in meanwhile: http://stackoverflow.com/questions/30562642/play-framework-routes-assets-at-compilation-error

**Comment by hendisantika** [comment]
I see that.

OK. I will refer to stackoverflow.

Thanks @pvoznenko
